### ISSUE TITLE
E3D PZ Probe

### ISSUE THREAD

**Issue by tamebits** [RobertLorincz/Smart-Orbiter-SO3#6]
Although from the outside it looks as if there was no way to do it, I wanted to double check if there is a way to mount an [E3D PZ Probe](https://e3d-online.com/blogs/news/introducing-pz-probe?srsltid=AfmBOorNBWhNDNfz_zsfhCeCqcN3uTDDVMGhIByBPhx5bz2lMuKGHnjZ) into SO3? This would be an awesome combination.

But it looks like the heat sink is fully integrated into the extruder body.

![image](https://github.com/user-attachments/assets/b3c21434-15e9-4314-87a1-0f4d48cf8b4a)

**Comment by RobertLorincz** [comment]
In the way this design is done, its not possible to implement it into the SO3...

**Comment by Tomblarom** [comment]
I'm using SO3 in combo with a Cartographer3D. I made a neat design, so that it's integrated in the fan and [posted about it here](https://www.facebook.com/groups/705637896767655/posts/1387416425256462).

![image](https://github.com/user-attachments/assets/bc8f70dc-0852-409d-81a6-0442f82c801b)

For Cartographer3D there is a new mode called [Survey Touch](https://docs.cartographer3d.com/cartographer-probe/classic-vs-survey-touch). It uses the electrial interference, to detect whether the nozzle touched the bed, functionwise very similar to the E3D PZ Probe. Sure it is not as neatly integrated, but still one of the most precise probes that are available right now.

**Comment by RobertLorincz** [comment]
nice design.

**Comment by tamebits** [comment]
I’m currently working on a similar solution for beacon probe. I’m still thinking about leaving it in der carrier so I don’t need one for each tool head.
